spring:
  application:
    name: api-product-service


  datasource:
    url: jdbc:postgresql://localhost:5432/products
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: other.server.local
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${random.value}

server:
  port: 0