spring:
  application:
    name: gateway


  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product-service
              uri: lb://api-product-service
              predicates:
                - Path=/product/**
              filters:
                - RewritePath=/product(?<segment>/?.*), /graphql\${segment}
            - id: client-service
              uri: lb://api-client-service
              predicates:
                - Path=/client/**
            - id: order-service
              uri: lb://api-order-service
              predicates:
                - Path=/order/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: false
